export const restArray = [
  {
    id: 1,
    title: "Pizza-plus",
    time: 50,
    rating: 4.5,
    price: 9,
    type: "Pizza",
    image: "pizza-plus.jpg",
  },
  {
    id: 2,
    title: "Tanuki",
    time: 50,
    rating: 4.5,
    price: 9,
    type: "Pizza",
    image: "tanuki.jpg",
  },
  {
    id: 3,
    title: "FoodBand",
    time: 50,
    rating: 4.5,
    price: 9,
    type: "Pizza",
    image: "food-band.jpg",
  },
  {
    id: 4,
    title: "Greedy-pizza",
    time: 50,
    rating: 4.5,
    price: 12,
    type: "Pizza",
    image: "greedy-pizza.jpg",
  },
  {
    id: 5,
    title: "Food point",
    time: 50,
    rating: 4.5,
    price: 9,
    type: "Pizza",
    image: "food-point.jpg",
  },
  {
    id: 6,
    title: "PizzaBurger",
    time: 50,
    rating: 4.5,
    price: 9,
    type: "Pizza",
    image: "pizza-burger.jpg",
  },
];
